{{- if .Values.ingress.enabled -}}
{{- $fullName := include "iiif.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "iiif.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if .Values.fester.enabled }}
          {{- range .paths.fester }}
          - path: {{ . }}
            backend:
              serviceName: {{ $.Release.Name }}-fester
              servicePort: {{ $.Values.fester.fester.port }}
          {{- end }}
          {{- end }}
          {{- if .Values.cantaloupe.enabled }}
          {{- range .paths.cantaloupe }}
          - path: {{ . }}
            backend:
              serviceName: {{ $.Release.Name }}-cantaloupe
              servicePort: {{ $.Values.cantaloupe.cantaloupe.port }}
          {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
