{{- if .Values.ingress.enabled -}}
{{- $fullName := "test-iiif" -}}
{{- $svcFesterName := "test-fester" -}}
{{- $svcFesterPort := 8888 -}}
{{- $svcCantaloupeName := "test-cantaloupe" -}}
{{- $svcCantaloupePort := 8182 -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "iiif.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths.fester }}
          - path: {{ . }}
            backend:
              serviceName: {{ $svcFesterName }}
              servicePort: {{ $svcFesterPort }}
          {{- end }}
          {{- range .paths.cantaloupe }}
          - path: {{ . }}
            backend:
              serviceName: {{ $svcCantaloupeName }}
              servicePort: {{ $svcCantaloupePort }}
          {{- end }}
    {{- end }}
  {{- end }}
