ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: iiif.sinaimanuscripts.library.ucla.edu
      paths:
        cantaloupe:
          - "/"
  tls:
    - secretName: prod-sinai-iiif-tls
      hosts:
        - iiif.sinaimanuscripts.library.ucla.edu

resources: {}

fester:
  enabled: false

cantaloupe:
  enabled: true
  resources:
    limits:
      cpu: 4000m
      memory: 13Gi
    requests:
      cpu: 100m
      memory: 256m
  replicaCount: 2
  ingress:
    enabled: false
  image:
    repository: "uclalibrary/cantaloupe-ucla"
    tag: "4.1.7-3"
  imagePullSecrets:
    - name: services-dockerhub-creds
  cantaloupe:
    jvm:
      corecount: 4
    env:
      CANTALOUPE_ENDPOINT_ADMIN_ENABLED: "true"
      CANTALOUPE_CACHE_SERVER_DERIVATIVE_ENABLED: "true"
      CANTALOUPE_CACHE_SERVER_DERIVATIVE: "S3Cache"
      CANTALOUPE_CACHE_SERVER_DERIVATIVE_TTL_SECONDS: "0"
      CANTALOUPE_CACHE_SERVER_PURGE_MISSING: "true"
      CANTALOUPE_CACHE_SERVER_RESOLVE_FIRST: "true"
      CANTALOUPE_PROCESSOR_SELECTION_STRATEGY: "ManualSelectionStrategy"
      CANTALOUPE_MANUAL_PROCESSOR_JP2: "KakaduNativeProcessor"
      CANTALOUPE_S3CACHE_ENDPOINT: "s3.us-west-2.amazonaws.com"
      CANTALOUPE_S3SOURCE_ENDPOINT: "s3.us-west-2.amazonaws.com"
      CANTALOUPE_S3SOURCE_BASICLOOKUPSTRATEGY_PATH_SUFFIX: ".jpx"
      CANTALOUPE_SOURCE_STATIC: "S3Source"
      CANTALOUPE_DELEGATE_SCRIPT_ENABLED: "true"
      CANTALOUPE_DELEGATE_SCRIPT_PATHNAME: "/usr/local/cantaloupe/delegates.rb"
      CANTALOUPE_SOURCE_DELEGATE: "true"
      DELEGATE_URL: "https://raw.githubusercontent.com/UCLALibrary/cantaloupe-delegate/master/lib/delegates.rb"
      CANTALOUPE_ENDPOINT_API_ENABLED: "true"
      HEAP_SIZE: "12g"
      CANTALOUPE_S3SOURCE_CHUNKING_ENABLED: "false"
      CANTALOUPE_S3SOURCE_CHUNKING_CACHE_ENABLED: "false"
    envSecrets:
      CANTALOUPE_ENDPOINT_ADMIN_SECRET: "cantaloupe-secrets"
      CANTALOUPE_S3CACHE_ACCESS_KEY_ID: "cantaloupe-secrets"
      CANTALOUPE_S3CACHE_SECRET_KEY: "cantaloupe-secrets"
      CANTALOUPE_S3SOURCE_ACCESS_KEY_ID: "cantaloupe-secrets"
      CANTALOUPE_S3SOURCE_SECRET_KEY: "cantaloupe-secrets"
      CANTALOUPE_S3SOURCE_BASICLOOKUPSTRATEGY_BUCKET_NAME: "cantaloupe-secrets"
      CANTALOUPE_S3CACHE_BUCKET_NAME: "cantaloupe-secrets"
      CIPHER_KEY: "cantaloupe-secrets"
      CIPHER_TEXT: "cantaloupe-secrets"
      CANTALOUPE_ENDPOINT_API_USERNAME: "cantaloupe-secrets"
      CANTALOUPE_ENDPOINT_API_SECRET: "cantaloupe-secrets"

