ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
  hosts:
    - host: ingest.iiif.library.ucla.edu
      paths:
        fester:
          - "/"
  tls:
    - secretName: prod-ingest-iiif-tls
      hosts:
        - ingest.iiif.library.ucla.edu

resources: {}

fester:
  enabled: true
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
  replicaCount: 1
  ingress:
    enabled: false
  image:
    repository: "uclalibrary/fester"
    tag: "0.18.0"
  imagePullSecrets:
    - name: services-dockerhub-creds
  fester:
    env:
      FESTER_URL: "https://iiif.library.ucla.edu"
      IIIF_BASE_URL: "https://iiif.library.ucla.edu/iiif/2"
      FESTER_S3_REGION: "us-west-2"
      FESTERIZE_VERSION: "0.3.1"
      AV_DEFAULT_AUDIO_THUMBNAIL_URL: "https://static.library.ucla.edu/audio_icon.svg"
      AV_DEFAULT_VIDEO_THUMBNAIL_URL: "https://static.library.ucla.edu/video_icon.svg"
    envSecrets:
      FESTER_S3_BUCKET: "fester-secrets"
      FESTER_S3_SECRET_KEY: "fester-secrets"
      FESTER_S3_ACCESS_KEY: "fester-secrets"

cantaloupe:
  enabled: false
