# UCLALib values for shoreline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/surfliner/surfliner/shoreline_discovery_app
  name: shoreline_discovery_app
  tag: stable
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts: ['shoreline.library.ucla.edu']
  tls: []

resources: {}

shoreline:
  access: Public
  db_setup_command: "db:migrate"
  geoblacklightDownloadPath: /data/tmp/cache/downloads
  provenance: "UC Santa Barbara"
  theme: "ucsb"
  # whether to ingest fixture data during deployment
  sample_data:
  suppressTools: false
  solr:
    collectionName: collection1
  email:
    contact_email: shoreline@example.edu
    delivery_method: letter_opener_web # or: smtp
    # see: https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
    # smtp_settings:
    #   address: smtp.example.edu
    #   port: 587
    #   user_name: username
    #   password: password
    #   authentication: plain

# Configuration for solr chart
# see: https://github.com/helm/charts/blob/master/incubator/solr/values.yaml
solr:
  image:
    repository: solr
    tag: 8.6.3

# Configuration for postgresql chart
# see: https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
postgresql:
  nameOverride: database
  image:
    repository: bitnami/postgresql
    tag: 12.4.0
  enabled: true
  postgresqlUsername: shoreline-discovery
  postgresqlPassword: shorelinepass
  postgresqlDatabase: shoreline-discovery
  servicePort: 5432
  persistence:
    size: 10Gi

geoserver:
  admin:
    password: shorelinegeo
  persistence:
    enabled: true
  ingress:
    enabled: true
    hosts: ['geoserver.local']
    tls: []

tolerations: []

affinity: {}
